#title: Rights statitics
#tags: rights,pie chart

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?label (COUNT(?label) AS ?count) WHERE {
  ?record a/skos:broader* <https://www.glaciersinarchives.org/id/type/work> .
  ?record dcterms:rights ?label .
} GROUP BY ?label
